### ISSUE TITLE
Rules Engine Config Pages

### ISSUE THREAD

**Issue by galthaus** [rackn/digitalrebar-ux#160]
Feature request for adding pages to manipulate Rule Engine sets.

This is similar but different than the provisioner.  Similar scope to start.

@VictorLowther has details about the syntax and format.  The idea is this would be where
rule sets could be created, imported, edited, and seen.  Not sure about status and other things
but the basic API is there.

This will need some work to make sure the rule_engine is running, added to the revproxy path, and capabilities are enabled and added.

We should also have a design discussion on the starting points.  HERE!

**Comment by zehicle** [comment]
The initial pass of this was done with #254 - I'm going to close this with the understanding that we'll keep improving it.
