### ISSUE TITLE
Capabilities Editor

### ISSUE THREAD

**Issue by galthaus** [rackn/digitalrebar-ux#162]
@VictorLowther is adding the ability create superset capabilities.
The idea is that SUPERUSER just includes Other capabilities.

We should be able to create those and then admins can give users those instead of clicking all 8 billion items.

**Comment by zehicle** [comment]
inital stages in #259 - missing add button at this time,

**Comment by zehicle** [comment]
this is functioning - default DR_ capabilities themselves still need work
