### ISSUE TITLE
Node role log has issues

### ISSUE THREAD

**Issue by galthaus** [rackn/digitalrebar-ux#199]
I've been doing a lot of retrying and watching.  Something is funky.  Like I had a node role that succeeded but still showed the failure from the previous run.  If I hard refresh, it shows the success, but doesn't update or show anything.  It just stop refreshing or so it seems.

**Comment by galthaus** [comment]
If I leave the now successful node role and go back, it will reload the correct node role log.

**Comment by Meshiest** [comment]
#200
