### ISSUE TITLE
Install OS wizard ignores os selector

### ISSUE THREAD

**Issue by galthaus** [rackn/digitalrebar-ux#257]
I provisioned 3 bare metal nodes (kvm instances).
Used the OS install wizard to select ubuntu-1404 (from default centos7.2).
The UX seems to have generated stuff correctly, but only one node had its node roles added and 
none had ubuntu-14.04 configured.

I add the node roles to the two that didn't get them and used attrib update to set the OS and that seemed to work for the two nodes done this way.

I suspect core has an issue with multi-node bare metal items.  Not sure though.

**Comment by zehicle** [comment]
fixed by creating two transactions in the API
