### ISSUE TITLE
Cannot add new nodes using metal

### ISSUE THREAD

**Issue by aledbf** [rackn/digitalrebar-ux#283]
![captura de pantalla 2016-10-21 a las 9 14 16 p m](https://cloud.githubusercontent.com/assets/161571/19615279/5e529a02-97d3-11e6-87d7-7173095ad2cb.png)

If I add a new provider appears in the list without metal as option

**Comment by aledbf** [comment]
@galthaus ping

**Comment by zehicle** [comment]
Metal is added via discovery or API only.  At some point, we plan to have a
metal provider that uses pools.

**Comment by aledbf** [comment]
@zehicle what it means? I'm trying to install a cluster of 4 Intel nuc with CoreOS (or Ubuntu).
I saw this https://www.youtube.com/watch?v=Zb16qk0l3Xw and thought that it was possible.
I'm sorry but I don't know if this is supported.
Thanks

**Comment by zehicle** [comment]
@aledbf Gitter (https://gitter.im/digitalrebar/core) is a better channel to get interactive help.

It is possible - metal (like a NUC) is generally added to the system using the PXE discovery/provisioning process.  That means that you have to get the provisioning infrastructure set up. That requires understanding your network environment - something that often requires some 1x1 guidance.

If you already have the nodes and just want to add them to the system, use the ./deploy/add-from-ssh.sh to join them.

**Comment by aledbf** [comment]
@zehicle thanks!
