### ISSUE TITLE
Use of existing nodes requires --con-provisioner

### ISSUE THREAD

**Issue by aledbf** [rackn/digitalrebar-ux#295]
Without `--con-provisioner` is not possible to use an existing node (nodes added with `add-from-ssh.sh`). This blocks the creation of kubernetes cluster.
![captura de pantalla 2016-11-17 a las 9 57 10 a m](https://cloud.githubusercontent.com/assets/161571/20390203/828af75a-acac-11e6-92f1-2c90f8ff09af.png)

**Comment by zehicle** [comment]
we should only allow existing if there's a provisioner running
