### ISSUE TITLE
Cannot add more than one node in Kubernetes Cluster Installation

### ISSUE THREAD

**Issue by Josh-Dunning** [rackn/digitalrebar-ux#372]
Clicking on "Add Nodes" button deletes current node and replaces it with a new worker node:
![image](https://cloud.githubusercontent.com/assets/29126427/26797844/f1ef7366-49f3-11e7-99cb-75f26c3f3e67.png)

![image](https://cloud.githubusercontent.com/assets/29126427/26797853/fc3270da-49f3-11e7-83ed-991f4f5c3fb2.png)

and displays the following console error message:
![image](https://cloud.githubusercontent.com/assets/29126427/26797870/0bd011a0-49f4-11e7-83e0-23ad56f8c3be.png)

**Comment by galthaus** [comment]
This is also better repeated in the field.

**Comment by Meshiest** [comment]
#376
